num_genes:             100
num_reads_to_simulate: 30000
prg_nesting_lvls:
    - 1
    - 3
    - 5
    - 10
snps_per_gene:
    - 1
    - 4
    - 10
coverages:
    - 15
    - 30
    - 60
    - 100
denovo_kmer_sizes:
    - 9
    - 11
    - 13
