containers:
  make_prg: "docker://quay.io/mbhall88/make_prg:29403da"
  pandora: "docker://quay.io/rmcolq/pandora:0.8.0"
  mafft: "docker://quay.io/biocontainers/mafft:7.475--h516909a_0"
  rasusa: "docker://quay.io/mbhall88/rasusa:0.6.0"
num_genes:             100
num_reads_to_simulate: 30000
prg_nesting_lvls:
  - 1
  - 3
  - 5
  - 10
snps_per_gene:
  - 1
  - 4
  - 10
coverages:
  - 15
  - 30
  - 60
  - 100
denovo_kmer_sizes:
  - 11
  - 13
  - 15
